version: '3'

volumes:
  workshop_postgresql_etc:
  workshop_postgresql_log:
  workshop_postgresql_data:
  workshop_liferay_data:

services:

  _workshop_liferay-base:
    image: liferay-base:7.4.3.102
    build:
      context: liferay-base
      dockerfile: Dockerfile

  workshop_portal:
    container_name: workshop_portal
    build:
      context: portal
      dockerfile: Dockerfile
    depends_on:
      - _workshop_liferay-base
      - workshop_database
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - ./portal/deploy:/opt/liferay/deploy
      - workshop_liferay_data:/opt/liferay/data/

  workshop_database:
    container_name: workshop_database
    image: postgres:11.22-alpine
    ports:
      - "5432:5432"
    volumes:
      - workshop_postgresql_etc:/etc/postgresql/
      - workshop_postgresql_log:/var/log/postgresql/
      - workshop_postgresql_data:/var/lib/postgresql/
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      INIT: "TRUE"
      POSTGRES_USER: liferay
      POSTGRES_DB: liferay
      POSTGRES_PASSWORD: liferay
