/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.workshop.holiday.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Holiday service. Represents a row in the &quot;HOLIDAY_Holiday&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.workshop.holiday.sb.model.impl.HolidayModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.workshop.holiday.sb.model.impl.HolidayImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Holiday
 * @generated
 */
@ProviderType
public interface HolidayModel extends BaseModel<Holiday> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a holiday model instance should use the {@link Holiday} interface instead.
	 */

	/**
	 * Returns the primary key of this holiday.
	 *
	 * @return the primary key of this holiday
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this holiday.
	 *
	 * @param primaryKey the primary key of this holiday
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this holiday.
	 *
	 * @return the uuid of this holiday
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this holiday.
	 *
	 * @param uuid the uuid of this holiday
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the holiday request ID of this holiday.
	 *
	 * @return the holiday request ID of this holiday
	 */
	public long getHolidayRequestId();

	/**
	 * Sets the holiday request ID of this holiday.
	 *
	 * @param holidayRequestId the holiday request ID of this holiday
	 */
	public void setHolidayRequestId(long holidayRequestId);

	/**
	 * Returns the create date of this holiday.
	 *
	 * @return the create date of this holiday
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this holiday.
	 *
	 * @param createDate the create date of this holiday
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the date request of this holiday.
	 *
	 * @return the date request of this holiday
	 */
	@AutoEscape
	public String getDateRequest();

	/**
	 * Sets the date request of this holiday.
	 *
	 * @param dateRequest the date request of this holiday
	 */
	public void setDateRequest(String dateRequest);

	/**
	 * Returns the is holiday of this holiday.
	 *
	 * @return the is holiday of this holiday
	 */
	public boolean getIsHoliday();

	/**
	 * Returns <code>true</code> if this holiday is is holiday.
	 *
	 * @return <code>true</code> if this holiday is is holiday; <code>false</code> otherwise
	 */
	public boolean isIsHoliday();

	/**
	 * Sets whether this holiday is is holiday.
	 *
	 * @param isHoliday the is holiday of this holiday
	 */
	public void setIsHoliday(boolean isHoliday);

	/**
	 * Returns the holiday name of this holiday.
	 *
	 * @return the holiday name of this holiday
	 */
	@AutoEscape
	public String getHolidayName();

	/**
	 * Sets the holiday name of this holiday.
	 *
	 * @param holidayName the holiday name of this holiday
	 */
	public void setHolidayName(String holidayName);

	@Override
	public Holiday cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}