/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.workshop.holiday.sb.model.impl;

import com.liferay.workshop.holiday.sb.model.Holiday;
import com.liferay.workshop.holiday.sb.service.HolidayLocalServiceUtil;

/**
 * The extended model base implementation for the Holiday service. Represents a row in the &quot;HOLIDAY_Holiday&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HolidayImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see HolidayImpl
 * @see Holiday
 * @generated
 */
public abstract class HolidayBaseImpl
	extends HolidayModelImpl implements Holiday {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a holiday model instance should use the <code>Holiday</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			HolidayLocalServiceUtil.addHoliday(this);
		}
		else {
			HolidayLocalServiceUtil.updateHoliday(this);
		}
	}

}